/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/accounts/': RouteRecordInfo<'/accounts/', '/accounts', Record<never, never>, Record<never, never>>,
    '/accounts/components/AccountForm': RouteRecordInfo<'/accounts/components/AccountForm', '/accounts/components/AccountForm', Record<never, never>, Record<never, never>>,
    '/accounts/components/AccountItem': RouteRecordInfo<'/accounts/components/AccountItem', '/accounts/components/AccountItem', Record<never, never>, Record<never, never>>,
    '/accounts/components/TagsInfo': RouteRecordInfo<'/accounts/components/TagsInfo', '/accounts/components/TagsInfo', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/accounts/index.vue': {
      routes: '/accounts/'
      views: never
    }
    'src/pages/accounts/components/AccountForm.vue': {
      routes: '/accounts/components/AccountForm'
      views: never
    }
    'src/pages/accounts/components/AccountItem.vue': {
      routes: '/accounts/components/AccountItem'
      views: never
    }
    'src/pages/accounts/components/TagsInfo.vue': {
      routes: '/accounts/components/TagsInfo'
      views: never
    }
    'src/pages/settings/index.vue': {
      routes: '/settings/'
      views: never
    }
    'src/pages/users/index.vue': {
      routes: '/users/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
